// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwtdirfmdakbwwjxdynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dGRpcmZtZGFrYnd3anhkeW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjg4NzcsImV4cCI6MjA3Mjc0NDg3N30.IdBjhaty0vlnpCztwu2lAMeR2FXt5FhJSwvQ4aJ8hQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});